from enum import StrEnum


class ReviewStatus(StrEnum):
    DRAFT = "draft"
    PUBLISHED = "published"
    MODERATED = "moderated"
    REMOVED = "removed"


class DisputeStatus(StrEnum):
    OPEN = "open"
    UNDER_REVIEW = "under_review"
    RESOLVED = "resolved"
    CLOSED = "closed"


class NotificationType(StrEnum):
    """Common in-app notification type codes (extensible strings allowed)."""

    RFQ_INVITED = "RFQ_INVITED"
    RFQ_INVITATION = "RFQ_INVITATION"
    RFQ_INVITE_RESPONSE = "RFQ_INVITE_RESPONSE"
    QUOTATION_RECEIVED = "QUOTATION_RECEIVED"
    QUOTE_RECEIVED = "QUOTE_RECEIVED"
    QUOTATION_ACCEPTED = "QUOTATION_ACCEPTED"
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    ORDER_REJECTED = "ORDER_REJECTED"
    ORDER_COMPLETED = "ORDER_COMPLETED"
    SHIPMENT_CREATED = "SHIPMENT_CREATED"
    SHIPMENT_UPDATE = "SHIPMENT_UPDATE"
    TRACKING_UPDATED = "TRACKING_UPDATED"
    INVOICE_ISSUED = "INVOICE_ISSUED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    CREDIT_NOTE_ISSUED = "CREDIT_NOTE_ISSUED"
    REFUND_PROCESSED = "REFUND_PROCESSED"
    DISPUTE_OPENED = "DISPUTE_OPENED"
    DISPUTE_RESOLVED = "DISPUTE_RESOLVED"
    SUPPLIER_VERIFIED = "SUPPLIER_VERIFIED"
    SUPPLIER_REJECTED = "SUPPLIER_REJECTED"
    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
    ACCOUNT_REACTIVATED = "ACCOUNT_REACTIVATED"
    TEAM_INVITATION = "TEAM_INVITATION"
    TEAM_MEMBER_JOINED = "TEAM_MEMBER_JOINED"
    SUPPLIER_VERIFICATION_SUBMITTED = "SUPPLIER_VERIFICATION_SUBMITTED"
    QUOTATION_WITHDRAWN = "QUOTATION_WITHDRAWN"
    QUOTATION_REJECTED = "QUOTATION_REJECTED"
    QUOTE_REJECTED = "QUOTE_REJECTED"
    NEGOTIATION_OPENED = "NEGOTIATION_OPENED"
    NEGOTIATION_OFFER = "NEGOTIATION_OFFER"
    CONVERSATION_MESSAGE = "CONVERSATION_MESSAGE"
    GENERAL = "GENERAL"


DISPUTE_STATUS_TRANSITIONS: dict[str, set[str]] = {
    DisputeStatus.OPEN: {DisputeStatus.UNDER_REVIEW, DisputeStatus.CLOSED},
    DisputeStatus.UNDER_REVIEW: {DisputeStatus.RESOLVED, DisputeStatus.CLOSED},
    DisputeStatus.RESOLVED: {DisputeStatus.CLOSED},
}
