
from __future__ import annotations

from typing import Any

ASSET_PREFIX = "/images/assets"

                                                        
SUBCATEGORIES: list[tuple[str, str, str, str, str, int]] = [
    ("bakery", "food", "Bakery & Confectionery", "Bread, pastries, and chocolate for cafes and retail.", "food/food1.png", 11),
    ("oils", "pantry", "Olive Oil & Honey", "Lebanese olive oil, honey, and cold-pressed staples.", "food/foodd1.png", 51),
    ("seafood", "meat", "Fresh Fish & Seafood", "Mediterranean catch delivered chilled on ice.", "food/food8.png", 31),
    ("poultry", "meat", "Poultry & Butchery", "Fresh chicken and beef cuts for kitchens.", "food/food9.png", 32),
    ("tea", "beverages", "Tea & Herbal Infusions", "Mountain herbs, zhourat, and loose-leaf blends.", "food/food7.png", 61),
    ("computing", "elect", "Computers & Peripherals", "Laptops, monitors, printers, and networking.", "elect/elect1.png", 111),
    ("mobile", "elect", "Phones, Audio & Wearables", "Smartphones, earbuds, watches, and cameras.", "elect/elect2.png", 112),
    ("lighting", "elect", "Lighting & Wiring", "LED bulbs, floodlights, cable, and sockets.", "elect/elect13.png", 113),
    ("blocks", "const", "Blocks, Bricks & Paving", "Masonry blocks, clay bricks, and pavers.", "const/const1.png", 141),
    ("powertools", "industrial", "Power & Hand Tools", "Drills, saws, ladders, and site tool kits.", "const/const5.png", 181),
    ("skincare", "care", "Skin, Lip & Body Care", "Soaps, lip care, sun care, and bath products.", "care/care5.png", 91),
    ("haircare", "care", "Hair Care", "Salon and retail shampoo and conditioner.", "care/care7.png", 92),
    ("desk", "office", "Desk Accessories", "Staplers, punches, trays, boards, and markers.", "office/office7.png", 131),
    ("kitchen", "home", "Cookware & Kitchen Tools", "Pots, pans, knives, and utensils.", "home/home1.png", 121),
    ("tableware", "home", "Tableware & Glassware", "Dinnerware and glass sets for homes and HORECA.", "home/home5.png", 122),
    ("hometextiles", "textiles", "Home Textiles", "Cushions, curtains, and rugs.", "home/home9.png", 101),
]

FEATURED_LANDING_SKUS = {
    "LEV-OIL-1L",
    "ZFI-HONEY",
    "BKT-MON-24",
    "CDR-BLOCK-20",
    "TYR-FISH-ICE",
    "PHR-LIP",
    "SPK-STAPLER",
    "LEV-OIL-5L",
}

                                                                                               
PRODUCTS_BY_SUPPLIER: dict[str, list[tuple[Any, ...]]] = {
    "levant": [
        ("LEV-OIL-1L", "Extra Virgin Olive Oil 1L", "carton", "Lebanon", 12, 3, "18.50", "480", "food/foodd1.png", "oils"),
        ("LEV-OIL-5L", "Extra Virgin Olive Oil 5L Tin", "carton", "Lebanon", 6, 3, "76.00", "160", "food/foodd1.png", "oils"),
        ("LEV-BREAD-MIX", "Bakery Bread Assortment", "carton", "Lebanon", 8, 2, "16.40", "140", "food/food1.png", "bakery"),
        ("LEV-PASTRY-MIX", "Pastry and Cake Assortment", "carton", "Lebanon", 8, 3, "19.80", "110", "food/food2.png", "bakery"),
        ("LEV-CHOC-MIX", "Assorted Chocolate", "carton", "Belgium", 6, 6, "22.00", "90", "food/food6.png", "bakery"),
        ("LEV-PANTRY-JAR", "Dry Goods Jars Assortment", "carton", "Lebanon", 10, 4, "14.50", "160", "food/food3.png", "pantry"),
        ("LEV-PASTA-5", "Durum Pasta Assortment", "carton", "Italy", 10, 5, "12.60", "300", "food/food4.png", "pantry"),
        ("LEV-PASTA-PENNE", "Durum Penne Rigate 500g", "carton", "Italy", 10, 5, "11.40", "260", "food/food4.png", "pantry"),
        ("LEV-MILK-PLANT", "Plant Milk and Nut Mix", "carton", "Lebanon", 8, 3, "15.20", "120", "food/food5.png", "dairy"),
        ("LEV-MILK-OAT", "Oat Milk 1L Barista Edition", "carton", "Lebanon", 8, 3, "17.60", "100", "food/food5.png", "dairy"),
    ],
    "bekaa": [
        ("BKT-LAPTOP-I5", "Business Laptop 14in", "piece", "China", 2, 14, "520.00", "28", "elect/elect1.png", "computing"),
        ("BKT-MON-24", "27in Office Monitor", "piece", "China", 4, 10, "145.00", "45", "elect/elect7.png", "computing"),
        ("BKT-PRINT-INK", "Color Inkjet Printer", "piece", "Vietnam", 2, 12, "89.00", "22", "elect/elect10.png", "computing"),
        ("BKT-ROUTER", "Dual-Band Wi-Fi Router", "piece", "China", 6, 8, "54.00", "60", "elect/elect11.png", "computing"),
        ("BKT-KB-RGB", "Keyboard and Mouse Set", "box", "China", 10, 5, "38.00", "120", "elect/elect12.png", "computing"),
        ("BKT-TABLET-10", "Tablet 11in with Stylus", "piece", "China", 4, 11, "165.00", "36", "elect/elect6.png", "computing"),
        ("BKT-CALC-12", "12-Digit Desktop Calculator", "piece", "China", 12, 5, "9.40", "150", "office/office1.png", "desk"),
        ("BKT-PHONE-5G", "5G Smartphone", "piece", "China", 4, 10, "280.00", "40", "elect/elect2.png", "mobile"),
        ("BKT-EARBUDS", "True Wireless Earbuds", "piece", "China", 12, 6, "42.00", "160", "elect/elect3.png", "mobile"),
        ("BKT-WATCH", "Smart Watch", "piece", "China", 8, 7, "89.00", "70", "elect/elect4.png", "mobile"),
        ("BKT-HEADSET", "Wireless Over-Ear Headphones", "piece", "China", 8, 6, "58.00", "90", "elect/elect5.png", "mobile"),
        ("BKT-CAM-DSLR", "Digital Camera Kit", "piece", "Japan", 2, 12, "640.00", "18", "elect/elect0.png", "mobile"),
        ("BKT-ACTION", "Action Camera", "piece", "China", 6, 8, "96.00", "50", "elect/elect9.png", "mobile"),
        ("BKT-CONSOLE", "Portable Game Console", "piece", "China", 4, 12, "210.00", "24", "elect/elect8.png", "mobile"),
    ],
    "cedar": [
        ("CDR-BLOCK-20", "Clay Bricks and Concrete Blocks", "piece", "Lebanon", 200, 3, "0.85", "8000", "const/const1.png", "blocks"),
        ("CDR-BLOCK-15", "Hollow Concrete Block 15cm", "piece", "Lebanon", 200, 3, "0.72", "9000", "const/const1.png", "blocks"),
        ("CDR-PAVER", "Concrete Paving Bricks", "piece", "Lebanon", 150, 3, "0.95", "5000", "const/const12.png", "blocks"),
        ("CDR-PAVER-GREY", "Interlocking Grey Pavers 6cm", "piece", "Lebanon", 150, 4, "1.05", "4200", "const/const12.png", "blocks"),
        ("CDR-REBAR-12", "Steel Rebar Bundle 12mm", "unit", "Turkey", 10, 5, "48.00", "180", "const/const2.png", "const"),
        ("CDR-REBAR-16", "Steel Rebar Bundle 16mm", "unit", "Turkey", 10, 5, "71.00", "120", "const/const2.png", "const"),
        ("CDR-TIMBER", "Structural Timber Beams", "piece", "Russia", 20, 6, "24.00", "220", "const/const3.png", "const"),
        ("CDR-PAINT-20", "Paint Buckets and Roller Kit", "piece", "Lebanon", 8, 4, "34.00", "110", "const/const4.png", "const"),
        ("CDR-PPE", "Safety Helmet and PPE Kit", "box", "China", 12, 4, "18.50", "160", "const/const7.png", "const"),
        ("CDR-DRILL-18", "Cordless Drill Kit 18V", "piece", "China", 4, 8, "89.00", "40", "const/const5.png", "powertools"),
        ("CDR-TOOLS", "Site Hand Tool Set", "box", "China", 8, 5, "28.00", "95", "const/const6.png", "powertools"),
        ("CDR-LADDER", "Aluminium Step Ladder", "piece", "China", 6, 7, "42.00", "55", "const/const10.png", "powertools"),
        ("CDR-SAW-CIRC", "Circular Saw 1400W", "piece", "China", 4, 8, "72.00", "35", "const/const11.png", "powertools"),
    ],
    "south": [
        ("TYR-FISH-ICE", "Chilled Whole Fish on Ice", "kg", "Lebanon", 10, 1, "14.50", "80", "food/food8.png", "seafood"),
        ("TYR-BREAM", "Whole Sea Bream (Ajaj), Cleaned", "kg", "Lebanon", 10, 1, "16.80", "60", "food/food8.png", "seafood"),
        ("TYR-MULLET", "Red Mullet (Sultan Ibrahim)", "kg", "Lebanon", 6, 1, "19.50", "40", "food/food8.png", "seafood"),
        ("TYR-CHICKEN", "Fresh Whole Chicken 1.2kg", "piece", "Lebanon", 8, 1, "9.80", "70", "food/food9.png", "poultry"),
        ("TYR-CHICKEN-L", "Fresh Whole Chicken 1.6kg", "piece", "Lebanon", 8, 1, "12.40", "60", "food/food9.png", "poultry"),
        ("TYR-BEEF-STK", "Fresh Beef Steaks", "kg", "Lebanon", 6, 1, "18.40", "45", "food/food10.png", "poultry"),
        ("TYR-BEEF-RIB", "Beef Ribeye Steaks, Grain-Fed", "kg", "Lebanon", 4, 2, "27.50", "30", "food/food10.png", "poultry"),
        ("TYR-BEEF-TEND", "Beef Tenderloin Medallions", "kg", "Lebanon", 4, 2, "32.00", "25", "food/food10.png", "poultry"),
    ],
    "pack": [
        ("SPK-TAPE", "Packing Tape Dispenser", "piece", "Lebanon", 24, 4, "4.80", "400", "office/office3.png", "packaging"),
        ("SPK-TAPE-REFILL", "Clear Packing Tape 48mm x 100m (6 rolls)", "box", "Lebanon", 24, 4, "7.90", "500", "office/office3.png", "packaging"),
        ("SPK-STORE", "Airtight Food Storage Set", "box", "Lebanon", 10, 5, "16.50", "180", "home/home2.png", "packaging"),
        ("SPK-STORE-XL", "Glass Meal-Prep Containers, 10 pcs", "box", "Lebanon", 10, 5, "24.00", "120", "home/home2.png", "packaging"),
        ("SPK-STAPLER", "Heavy-Duty Stapler with Staples", "piece", "China", 12, 4, "6.20", "220", "office/office2.png", "desk"),
        ("SPK-PUNCH", "Two-Hole Paper Punch", "piece", "China", 12, 4, "5.40", "180", "office/office4.png", "desk"),
        ("SPK-HILITE", "Highlighter Markers, 4 Colours", "box", "China", 24, 3, "2.60", "600", "office/office5.png", "desk"),
        ("SPK-CORK", "Cork Notice Board 60x90cm", "piece", "China", 6, 6, "14.00", "70", "office/office6.png", "desk"),
        ("SPK-TRAY", "Three-Tier Metal Document Tray", "piece", "China", 8, 6, "11.50", "90", "office/office7.png", "desk"),
    ],
    "zahle": [
        ("ZFI-HONEY", "Bekaa Wildflower Honey", "carton", "Lebanon", 8, 3, "21.00", "90", "food/foodd2.png", "oils"),
        ("ZFI-HONEY-THYME", "Thyme Blossom Honey 500g", "carton", "Lebanon", 8, 3, "24.50", "70", "food/foodd2.png", "oils"),
        ("ZFI-HONEY-OAK", "Oak Forest Honey 1kg", "carton", "Lebanon", 6, 3, "31.00", "50", "food/foodd2.png", "oils"),
        ("ZFI-OIL-3L", "Cold-Pressed Olive Oil 3L", "carton", "Lebanon", 6, 4, "46.00", "80", "food/foodd1.png", "oils"),
        ("ZFI-PULSES", "Bekaa Pulses and Grains Jar Set", "carton", "Lebanon", 10, 4, "13.20", "120", "food/food3.png", "pantry"),
        ("ZFI-PASTA-VILLAGE", "Village Pasta Shells 1kg", "carton", "Lebanon", 10, 4, "10.80", "140", "food/food4.png", "pantry"),
        ("ZFI-PASTRY", "Zahle Village Pastries Box", "carton", "Lebanon", 8, 2, "17.40", "60", "food/food2.png", "bakery"),
        ("ZFI-BREAD", "Stone-Oven Bread Assortment", "carton", "Lebanon", 8, 1, "14.90", "70", "food/food1.png", "bakery"),
    ],
    "tripoli": [
        ("SAF-MOP", "Plastic Spin Mop and Bucket", "piece", "Lebanon", 12, 5, "14.80", "160", "home/home7.png", "cleaning"),
        ("SAF-MOP-XL", "Heavy-Duty Spin Mop Set XL", "piece", "Lebanon", 8, 5, "21.50", "90", "home/home7.png", "cleaning"),
        ("SAF-MOP-HEAD", "Spin Mop Refill Heads (3 pack)", "box", "Lebanon", 24, 4, "5.90", "300", "home/home7.png", "cleaning"),
        ("SAF-STORE-5", "Food Storage Box Set, 5 pcs", "box", "Lebanon", 12, 5, "12.40", "200", "home/home2.png", "packaging"),
        ("SAF-STORE-20", "Kitchen Storage Box Set, 20 pcs", "box", "Lebanon", 6, 6, "34.00", "80", "home/home2.png", "packaging"),
        ("SAF-HAMPER", "Woven Laundry Hamper with Liner", "piece", "Lebanon", 6, 6, "19.80", "75", "home/home8.png", "home"),
        ("SAF-HAMPER-L", "Large Laundry Hamper 80L", "piece", "Lebanon", 6, 6, "24.50", "60", "home/home8.png", "home"),
        ("SAF-UTENSIL", "Kitchen Utensil and Board Set", "box", "Lebanon", 10, 5, "13.60", "110", "home/home4.png", "kitchen"),
    ],
    "keserwan": [
        ("PHR-COTTON", "Cotton Pads and Swabs", "box", "Lebanon", 16, 5, "6.40", "280", "care/care4.png", "pharma"),
        ("PHR-COTTON-XL", "Cotton Pads 120 ct Clinic Pack", "box", "Lebanon", 16, 5, "8.90", "220", "care/care4.png", "pharma"),
        ("PHR-SUN", "Sunscreen Lotion Pair SPF 30", "box", "EU", 12, 6, "11.20", "190", "care/care6.png", "skincare"),
        ("PHR-SUN-50", "Sunscreen Lotion Pair SPF 50+", "box", "EU", 12, 6, "13.80", "160", "care/care6.png", "skincare"),
        ("PHR-LIP", "Lip Balm and Lip Mask Set", "box", "Lebanon", 24, 4, "4.60", "320", "care/care5.png", "skincare"),
        ("PHR-BATH", "Lavender Bath Bomb and Soap Set", "box", "Lebanon", 12, 5, "9.80", "180", "care/care1.png", "skincare"),
        ("PHR-FOOT", "Foot Care Kit with Pumice", "box", "Lebanon", 12, 5, "7.40", "150", "care/care2.png", "skincare"),
        ("PHR-MAKEUP", "Makeup Palette and Brush Kit", "box", "Italy", 6, 8, "26.00", "80", "care/care3.png", "care"),
        ("PHR-HAIR", "Olive Shampoo and Conditioner Duo", "box", "Lebanon", 12, 5, "10.60", "170", "care/care7.png", "haircare"),
    ],
    "saida": [
        ("MSP-TEA-HERB", "Mountain Herbal Tea", "carton", "Lebanon", 12, 2, "9.60", "220", "food/food7.png", "tea"),
        ("MSP-TEA-ZHOURAT", "Zhourat Wild Flower Blend 250g", "carton", "Lebanon", 12, 2, "12.40", "140", "food/food7.png", "tea"),
        ("MSP-TEA-SAGE", "Sage and Mint Loose Tea 250g", "carton", "Lebanon", 12, 2, "8.90", "160", "food/food7.png", "tea"),
        ("MSP-TEA-CHAM", "Chamomile Tea, 25 Bags", "carton", "Lebanon", 12, 2, "7.80", "180", "food/food7.png", "tea"),
        ("MSP-TEA-ANISE", "Anise Tea, 25 Bags", "carton", "Lebanon", 12, 2, "7.60", "150", "food/food7.png", "tea"),
        ("MSP-COFFEE", "Roasted Coffee Beans 1kg Jar", "carton", "Lebanon", 6, 3, "18.90", "90", "food/food3.png", "beverages"),
        ("MSP-COFFEE-CARD", "Cardamom Coffee Blend 500g", "carton", "Lebanon", 6, 3, "11.20", "110", "food/food3.png", "beverages"),
        ("MSP-PANTRY", "Pantry Glass Jar Trio, Filled", "carton", "Lebanon", 6, 4, "16.40", "70", "food/food3.png", "pantry"),
    ],
    "baalbek": [
        ("SRC-DINNER", "Ceramic Dinnerware Set, 16 pcs", "box", "Lebanon", 8, 8, "28.00", "90", "home/home5.png", "tableware"),
        ("SRC-DINNER-24", "Ceramic Dinnerware Set, 24 pcs", "box", "Lebanon", 6, 8, "39.00", "60", "home/home5.png", "tableware"),
        ("SRC-GLASS", "Glass Pitcher and Tumbler Set", "box", "Lebanon", 10, 6, "16.80", "110", "home/homw6.png", "tableware"),
        ("SRC-GLASS-HORECA", "Tumbler Set, HORECA Case of 36", "box", "Lebanon", 6, 6, "29.50", "70", "home/homw6.png", "tableware"),
        ("SRC-COOK-SET", "Granite Cookware Set, 7 pcs", "box", "Turkey", 4, 9, "68.00", "40", "home/home1.png", "kitchen"),
        ("SRC-KNIFE", "Chef Knife Block Set", "box", "Turkey", 6, 9, "36.00", "55", "home/home3.png", "kitchen"),
        ("SRC-UTENSIL", "Olive Wood Utensil Set", "box", "Lebanon", 10, 6, "12.80", "100", "home/home4.png", "kitchen"),
        ("SRC-CLOCK", "Wall Clock", "piece", "Lebanon", 8, 7, "18.40", "70", "home/home12.png", "home"),
    ],
    "achrafieh": [
        ("LTX-CUSHION", "Cushion and Throw Set", "box", "Turkey", 8, 9, "24.00", "80", "home/home9.png", "hometextiles"),
        ("LTX-CUSHION-4", "Linen Cushion Covers, 4 pcs", "box", "Turkey", 10, 9, "15.60", "110", "home/home9.png", "hometextiles"),
        ("LTX-CURTAIN", "Blackout Curtain Pair 140x250", "piece", "Turkey", 6, 10, "32.00", "60", "home/home10.png", "hometextiles"),
        ("LTX-CURTAIN-XL", "Blackout Curtain Pair 200x280", "piece", "Turkey", 6, 10, "44.00", "45", "home/home10.png", "hometextiles"),
        ("LTX-SHEER", "Sheer Voile Curtain Pair", "piece", "Turkey", 6, 10, "21.00", "70", "home/home10.png", "hometextiles"),
        ("LTX-RUG", "Woven Area Rug 160x230", "piece", "Turkey", 4, 12, "78.00", "40", "home/home11.png", "hometextiles"),
        ("LTX-RUG-S", "Woven Area Rug 120x170", "piece", "Turkey", 4, 12, "49.00", "50", "home/home11.png", "hometextiles"),
        ("LTX-RUG-RUNNER", "Woven Hallway Runner 80x300", "piece", "Turkey", 4, 12, "56.00", "35", "home/home11.png", "hometextiles"),
    ],
    "jbeil": [
        ("NHR-BULB", "LED Bulb E27 9W", "piece", "China", 24, 5, "3.80", "400", "elect/elect13.png", "lighting"),
        ("NHR-BULB-12", "LED Bulb E27 12W", "piece", "China", 24, 5, "4.60", "360", "elect/elect13.png", "lighting"),
        ("NHR-BULB-E14", "LED Candle Bulb E14 6W", "piece", "China", 24, 5, "3.20", "300", "elect/elect13.png", "lighting"),
        ("NHR-CABLE", "Electrical Cable and Socket Kit", "box", "Turkey", 8, 7, "36.00", "90", "const/const8.png", "lighting"),
        ("NHR-CABLE-25", "Copper Cable 2.5mm, 100m Roll", "box", "Turkey", 6, 7, "58.00", "60", "const/const8.png", "lighting"),
        ("NHR-LIGHT", "LED Work Lights and Floodlight", "box", "China", 6, 8, "42.00", "70", "const/const9.png", "lighting"),
        ("NHR-FLOOD-50", "LED Floodlight 50W IP65", "piece", "China", 6, 8, "19.50", "90", "const/const9.png", "lighting"),
        ("NHR-FLOOD-100", "LED Floodlight 100W IP65", "piece", "China", 6, 8, "31.00", "60", "const/const9.png", "lighting"),
    ],
}
