export const APP_NAME = "TradeBay";

export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  verifyEmail: "/verify-email",
  verifyEmailSuccess: "/verify-email/success",
  resetPassword: "/reset-password",
  resetPasswordSuccess: "/reset-password/success",
  members: "/members",
  invitations: "/invitations",
  rolesNew: "/roles/new",
  roles: "/roles",
  permissions: "/permissions",
  acceptInvitation: "/accept-invitation",
  dashboard: "/dashboard",
  businesses: "/businesses",
  businessesNew: "/businesses/new",
  businessesVerify: "/businesses/new/verify",
  businessesComplete: "/businesses/new/complete",
  catalog: "/catalog",
  catalogNew: "/catalog/new",
  catalogProduct: (id: string) => `/catalog/${id}`,
  marketplace: "/inventory/products",
  inventory: "/inventory",
  inventoryProducts: "/inventory/products",
  inventoryProductNew: "/inventory/products/new",
  inventoryProduct: (id: string) => `/inventory/products/${id}`,
  inventoryCategories: "/inventory/categories",
  inventoryStock: "/inventory/stock",
  inventoryMovements: "/inventory/movements",
  cart: "/cart",
  suppliersDirectory: "/suppliers",
  supplierProfile: (id: string) => `/suppliers/${id}`,
  companyProfile: (id: string) => `/companies/${id}`,
  supplierProducts: (id: string) => `/inventory/products?supplier=${encodeURIComponent(id)}`,
  quotations: "/quotations",
  orders: "/orders",
  checkout: "/checkout",
  checkoutDetail: (id: string) => `/orders/checkouts/${id}`,
  tracking: "/tracking",
  trackingOrder: (id: string) => `/tracking/${id}`,
  notifications: "/notifications",
  procurement: "/procurement",
  procurementNew: "/procurement/new",
  procurementProductQuote: (productId: string) =>
    `/procurement/new/product?product=${encodeURIComponent(productId)}`,
  procurementSourcingNew: "/procurement/new/sourcing",
  procurementRfq: (id: string) => `/procurement/rfqs/${id}`,
  procurementOrder: (id: string) => `/procurement/orders/${id}`,
  procurementShipment: (id: string) => `/procurement/shipments/${id}`,
  finance: "/finance",
  financeInvoice: (id: string) => `/finance/invoices/${id}`,
  settings: "/settings",
  profile: "/settings/profile",
  changePassword: "/settings/password",
  sessions: "/settings/sessions",
  accountSuspended: "/account-suspended",
  audit: "/audit",
  conversations: "/conversations",
  conversation: (id: string) => `/conversations/${id}`,
  negotiation: (id: string) => `/negotiations/${id}`,
  businessPlanner: "/business-planner",
  businessPlannerNew: "/business-planner/new",
  businessPlannerPlan: (id: string) => `/business-planner/${id}`,
  aiSourcing: "/ai-sourcing",
  terms: "/terms",
  privacy: "/privacy",
  admin: {
    home: "/admin",
    businesses: "/admin/businesses",
    buyers: "/admin/businesses?type=buyer",
    businessDetail: (id: string) => `/admin/businesses/${id}`,
    suppliers: "/admin/suppliers",
    categories: "/admin/categories",
    products: "/admin/products",
    productDetail: (id: string) => `/admin/products/${id}`,
    settlements: "/admin/settlements",
    finance: "/admin/finance",
    users: "/admin/users",
    roles: "/admin/roles",
    permissions: "/admin/permissions",
    audit: "/admin/audit",
    settings: "/admin/settings",
  },
} as const;

export const DOMAIN_NAV = [
  { href: ROUTES.dashboard, label: "Overview", key: "dashboard" },
  { href: ROUTES.inventory, label: "Inventory", key: "inventory" },
  { href: ROUTES.procurement, label: "Procurement", key: "procurement" },
  { href: ROUTES.conversations, label: "Conversations", key: "conversations" },
  { href: ROUTES.finance, label: "Finance", key: "finance" },
  { href: ROUTES.settings, label: "Settings", key: "settings" },
  { href: ROUTES.members, label: "Members", key: "members" },
  { href: ROUTES.roles, label: "Roles", key: "roles" },
  { href: ROUTES.invitations, label: "Invitations", key: "invitations" },
] as const;

export const DASHBOARD_DOMAINS = [
  {
    key: "identity",
    title: "Identity",
    description: "Users, businesses, memberships, and permissions.",
    href: ROUTES.settings,
  },
  {
    key: "marketplace",
    title: "Marketplace",
    description: "Products, pricing, and supplier listings.",
    href: ROUTES.catalog,
  },
  {
    key: "procurement",
    title: "Procurement",
    description: "RFQs, quotations, and negotiations.",
    href: ROUTES.procurement,
  },
  {
    key: "communication",
    title: "Communication",
    description: "Conversations and messages between buyers and suppliers.",
    href: ROUTES.conversations,
  },
  {
    key: "negotiation",
    title: "Negotiation",
    description: "Compare offers and counter-offers in a deal.",
    href: ROUTES.conversations,
  },
] as const;
